# -*- coding: utf-8 -*-
"""Project_ML_AutoImportKaggle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tG6nM6w9P0CthFNK1UmN3tVdjZIqoxkG

# Install Requirements
"""

!pip install opendatasets
!pip install pandas
!pip install kaggle

"""# Import Library"""

from google.colab import drive
import pandas as pd
import zipfile

"""# Mount Drive to Program"""

drive.mount("/content/gdrive")

"""# Mount Kaggle to Program

Ensure that your Kaggle key is stored in your Google Drive. If you haven't saved the file yet, follow these steps:

1.   Log in to your Kaggle account, select setting, navigate to the API
2.   Section, and select "Expire API Token" to remove any previous tokens. Click on "Create New API Token" to download the 'kaggle.json' file to your device.
"""

# Make kaggle folder in root google colab program
!mkdir ~/.kaggle

# Adjust to file location and copy kaggle json to folder kaggle in root
!cp gdrive/MyDrive/kaggle.json ~/.kaggle/

# change kaggle permission
!chmod 600 ~/.kaggle/kaggle.json

# Insert link kaggle
kaggle_link = 'https://www.kaggle.com/datasets/karthickveerakumar/salary-data-simple-linear-regression'

# Split some string
dataset_name = kaggle_link.split('datasets/')[1]
namadf = dataset_name.split('/')[1]

# download dateset from kaggle
!kaggle datasets download -d {dataset_name}

# zip file download
!unzip -q ./{namadf}.zip -d .

# zip file handler
zip = zipfile.ZipFile(f'{namadf}.zip')

# list available files in the container
isilist = zip.namelist()

# membaca dataset dan mengubahnya menjadi dataframe
data = pd.read_csv(f'{isilist[0]}')
data